plugins {
    id 'com.android.application'
}

android {
    namespace 'it.paolo.pronosticicalcio'
    compileSdk 35

    defaultConfig {
        applicationId 'it.paolo.pronosticicalcio'
        minSdk 24
        targetSdk 35
        versionCode 13
        versionName '2.2'

        def apiFootballKey = System.getenv('API_FOOTBALL_KEY') ?: ''
        def escapedKey = apiFootballKey.replace('\\', '\\\\').replace('"', '\\"')
        buildConfigField 'String', 'API_FOOTBALL_KEY', '"' + escapedKey + '"'

        def footballDataKey = System.getenv('FOOTBALL_DATA_KEY') ?: ''
        def escapedFootballDataKey = footballDataKey.replace('\\', '\\\\').replace('"', '\\"')
        buildConfigField 'String', 'FOOTBALL_DATA_KEY', '"' + escapedFootballDataKey + '"'
    }

    buildFeatures { buildConfig true }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
